language: minimal
sudo: required
env:
  global:
  - GRAAL_VERSION="1.0.0-rc9"
matrix:
  fast_finish: true
  include:
  - os: linux
    env:
    - GRAAL_ARCH=linux
    - NATIVE_SUFFIX=_linux
    - NATIVE_FLAGS=--static
  - os: osx
    env:
    - GRAAL_ARCH=macos
    - NATIVE_SUFFIX=_macos
    - GRAAL_HOME_SUFFIX=Contents/Home/
script:
- export GRAALVM_PKG=https://github.com/oracle/graal/releases/download/vm-${GRAAL_VERSION}/graalvm-ce-${GRAAL_VERSION}-${GRAAL_ARCH}-amd64.tar.gz
- curl --fail --silent --location --retry 3 ${GRAALVM_PKG} | gunzip | tar x -C ./
- export GRAAL_HOME=$(pwd)/graalvm-ce-${GRAAL_VERSION}/${GRAAL_HOME_SUFFIX}
- make native
deploy:
  provider: releases
  api_key:
    secure: c/GQ5SIMoDXhTjLjwJ5ccDYySq5u3ae3MfG8Kv3Dj8Kc6uKSNXtTDKgb6wAWE7Bia3PX+7UsBmdT0V/5PrG3o7Lzq9F4Gvcw9noArPqkEbD3tscs/8qb/29xuwGW4MMrysDuwxkhbtD4fcteh5Rkxk1uuWFTIpLgu9mJcMjH4OM2ZM9FVZeqXloJO7/J9FMZmEJPCWIO8mpxCgu7lxSv+kRaroivS7SghqMkjzqxVQnSAmL37tOsDCvUUZdgwfmbcGjxhiydE4UzdnG9KI/NB6OJ4yfwbfZlha8/A7S9cIyc8flMoXM1DheZ64OyfCDGwkAWqhBuo+wdVOuB5uYjy2unrQTh6YPhJfaXNjNst+1utVNAMNnxaVrpRa5m7vWogzoRTBH8HELiOxxS5bo8pqSx4PcChfJO6gqQXOP74hBLz4+8iB1f3m3n+2bGVDsczDCY42MpFqq4RO4tPz2OgYpfGzjC5GhclpuvCy7Xi0uZuqbAq3mtN8++ZxUaIDvTS/EseD119+QOtqe07RamUmmnzIwa2NeaNDpiwOT/u3ebq0QspXwX85m8fIMTmDNFUxWHjXud2bJ1Xkhq6xefPTKS70v1GfO2JRRfx2h2H1A+4/IBl8c6fkytBIr0LNiwv++EIOJZkV49Z2OPGSUt2XNWYbon1kaqoAEX5NMxoxM=
  file: "./bin/jpx${NATIVE_SUFFIX}"
  on:
    repo: kppk/jpx
    tags: true