language: minimal
sudo: required
services:
  - docker
matrix:
  include:
    - os: linux
    - os: osx
env:
  global:
    - GRAAL_VERSION="1.0.0-rc9"
    - JDK8_UPDATE_VERSION="192"
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v $(pwd):/src -w /src oracle/graalvm-ce:1.0.0-rc9 /bin/bash -c 'export GRAAL_HOME=$JAVA_HOME && export NATIVE_SUFFIX=_linux && export NATIVE_FLAGS=--static && make native'; sudo chown travis:travis ./bin/*; fi
  - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]
      then
        export GRAALVM_PKG=https://github.com/oracle/graal/releases/download/vm-${GRAAL_VERSION}/graalvm-ce-${GRAAL_VERSION}-macos-amd64.tar.gz
        curl --fail --silent --location --retry 3 ${GRAALVM_PKG} | gunzip | tar x -C ./
        export GRAAL_HOME=$(pwd)/graalvm-ce-${GRAAL_VERSION}/Contents/Home/
        export NATIVE_SUFFIX=_macos
        make native
      fi