language: minimal
sudo: required
dist: xenial
env:
  global:
  - GRAAL_VERSION="1.0.0-rc13"
matrix:
  fast_finish: true
  include:
  - os: linux
    env:
    - GRAAL_ARCH=linux
    - NATIVE_SUFFIX=_linux
    - NATIVE_FLAGS=--static
  - os: osx
    env:
    - GRAAL_ARCH=macos
    - NATIVE_SUFFIX=_macos
    - GRAAL_HOME_SUFFIX=Contents/Home/
script:
- export GRAALVM_PKG=https://github.com/oracle/graal/releases/download/vm-${GRAAL_VERSION}/graalvm-ce-${GRAAL_VERSION}-${GRAAL_ARCH}-amd64.tar.gz
- curl --fail --silent --location --retry 3 ${GRAALVM_PKG} | gunzip | tar x -C ./
- export GRAAL_HOME=$(pwd)/graalvm-ce-${GRAAL_VERSION}/${GRAAL_HOME_SUFFIX}
- make native
deploy:
  provider: releases
  api_key:
    secure: SOkB1WYkCdnDWGn2UZBOuBb/OFG7pwSXw3Tbt1d5R+NqCiYHAn5gdInc+jtHOVxs05a17Ne9a+ZSrEJc+eDXnxZCc/ucpXa2CxaYgru63VTaCN92mDeLELTCKveRppLYbb8/ovuitYJhEaOYDPaWTFBtghq9/Y52OSk6Esg7Tn56aiJRhLsFCf52A6z/BEqkWMfFoHrr8zK8cvGIAQRgj5YSo7ZnqKKOEaCjZ8DYnY94LxJ8Juv5hYL/m6GG7WC0XDmM+Z93nTgNYRNMUHvWk6YXulbIzA4VkVzWtItKjwU45/GZPee9f1JZEguBQ9wKfxvRiE9g0nJjN8y0jajRW2N+Y/68801L5ulnWxxPuC8TuexssWInLUdiPXfbBLlCPoSOvUtXRR+MTxH7KK0S1WEYLzB8i+p8wpWhmTqvTe6FE9faI3ZcUaFakQ9sQudtZ5ufxkIKN2OLrX9nJemD/+DIlz88SyyM3jGQhZTvBlGqjWkqgGJMBZGLwWRWbhe4+sxUdZggqJbZSiEUhENRhoNHuxZVF+JRa6SW35ncoY7qCklmtrIOcSJEHNQp6WnkipOnHVQvpj/HUs5zWoJrVbZo3CQQCSYOJ09APZw800qJajLNsCH1wM2MFlGfRdhUXbfVvz0a2C1Ot2nEyM3UdHbUGXEe0QQy6mSLTL/0Vvw=
  file: "./bin/jpx${NATIVE_SUFFIX}"
  skip_cleanup: true
  on:
    repo: kppk/jpx
    tags: true