language: minimal
sudo: required

env:
  global:
    - GRAAL_VERSION="1.0.0-rc9"

matrix:
  fast_finish: true
  include:
    - os: linux
      env:
        - GRAAL_ARCH=linux
        - NATIVE_SUFFIX=_linux
        - NATIVE_FLAGS=--static
        - GRAAL_HOME=$(pwd)/graalvm-ce-${GRAAL_VERSION}/
    - os: osx
      env:
        - GRAAL_ARCH=macos
        - NATIVE_SUFFIX=_macos
        - GRAAL_HOME=$(pwd)/graalvm-ce-${GRAAL_VERSION}/Contents/Home/

script:
  - export GRAALVM_PKG=https://github.com/oracle/graal/releases/download/vm-${GRAAL_VERSION}/graalvm-ce-${GRAAL_VERSION}-${GRAAL_ARCH}-amd64.tar.gz
  - curl --fail --silent --location --retry 3 ${GRAALVM_PKG} | gunzip | tar x -C ./
  - make native
