language: minimal
sudo: required
env:
  global:
  - GRAAL_VERSION="1.0.0-rc9"
matrix:
  fast_finish: true
  include:
  - os: linux
    env:
    - GRAAL_ARCH=linux
    - NATIVE_SUFFIX=_linux
    - NATIVE_FLAGS=--static
  - os: osx
    env:
    - GRAAL_ARCH=macos
    - NATIVE_SUFFIX=_macos
    - GRAAL_HOME_SUFFIX=Contents/Home/
script:
- export GRAALVM_PKG=https://github.com/oracle/graal/releases/download/vm-${GRAAL_VERSION}/graalvm-ce-${GRAAL_VERSION}-${GRAAL_ARCH}-amd64.tar.gz
- curl --fail --silent --location --retry 3 ${GRAALVM_PKG} | gunzip | tar x -C ./
- export GRAAL_HOME=$(pwd)/graalvm-ce-${GRAAL_VERSION}/${GRAAL_HOME_SUFFIX}
- make native
deploy:
  provider: releases
  api_key:
    secure: "ATBIuZTMuRs7Csx2vQtxi73gCgSYh3NFwBuVJrC4glEBM+3gXO4rsXxNB8vS9/5348McqfNjkTr6Qx2nei8LVygUb9vb2wSZfswzOgS34mMtBFmOOy0lo3jV5JEoRXwSocXQRjsfrplP/aDM0QkmXnrC5DfNQhBV3zM+nnLyV0BD62xbT276J7ic1JrwC9qj12shISLi0npAdj5J6RfWd2IviknxhtGu56JLmFqIfSTzNbsTUOKRjolYqXYoVk6ylPJfY+oStWcAOtRXZ8jsVCwW+Ul7f6d80k81/64JZ6r/pgQxKN9fJ7rfYBUN7WZISG2/oJTbk7bI0DZaKMEawgF5ADGjiK6tWNKXygKFBMo2OGXTikwrunsdj80KVllvWtcYQt6XGZUJTkeDTkH9+bWGerMPWJKu/XFqwbs1n0ELqFaqPXXu5UYMXA8rGbryygkNwFjsKs7l9PnAGstYGKDzrmuGLvJrTC6/k3T0bqAVwb3xiM7BmWXQ+k8YE5mU3RNiWYtBWTYm0i+lkAtHRaNVGSUY8lfn9ClXCO7jWlxxIfxIl/RUfhS/M4/nDOW+CV7Y6tVBQxpsxt/GeAsupUXMK0mCgn/OBmITU34E7cDO9pcOYrlYQvx3/zkD51oibhzCgLcCdrE7IR7ajJyLcNKImAvJMaJj9ys82x9WD+o="
  file: "./bin/jpx${NATIVE_SUFFIX}"
  on:
    repo: kppk/jpx
    tags: true