[pack]
name = "org.jpx" # the name of the main module
version = "0.1.0"    # the current version, obeying semver
authors = ["you@example.com"]

[bin]
main="org.jpx.Main"

[deps]
dep1="1.0.0"
'org.some.dep2'="2.0.3"
org_some_dep23="2.0.3"
dep3 = { path = "sub-project" }