[pack]
name = "org.jpx" # the name of the main module
version = "0.1.0"    # the current version, obeying semver
authors = ["you@example.com"]
java_release = "8"
type = "bin"

[bin]
main="org.jpx.Main"
